### ISSUE TITLE
ItunesConnectUser: required variable is not present

### ISSUE THREAD

**Issue by ksetrin** [bitrise-steplib/steps-deploy-to-itunesconnect-application-loader#8]
This happen sometimes and I can't understand why it's happen
I setup one project for auto deploy to App Store Connect. It works fine every time
Some later I setup one more project with the same `bitrise.yml`

I already upload 3 times with my current Workflow to App Store Connect and now it not upload

Always have the Error: ItunesConnectUser: required variable is not present

BUT, I have this one in Secret Environment Variables
And env `$ITUNES_CONNECT_USER` was be used in last uploads
Please, help me to understand what's the problem with step

```
    - deploy-to-itunesconnect-application-loader@0.9.4:
        inputs:
        - password: "$ITUNES_CONNECT_PASSWORD"
        - app_password: "$ITUNES_CONNECT_SPECIFIC_PASSWORD"
        - itunescon_user: "$ITUNES_CONNECT_USER"
        is_always_run: true
```
![image](https://downloads.intercomcdn.com/i/o/100371040/82d31df35b333455ed09bf87/image.png)

USER and PASSWORD valid (with it I upload later)

.ipa for generates correctly by xcode-archive@2.4.15

Please, help me
